---
- hosts:
  - ny-fw01
  gather_facts: no
  vars:
    ansible_connection: local
  vars_files:
    - "~/.clicap.vault.yml"
  tasks:
  - name: collect running configuration only
    action: clicap output="/tmp/clicap-%Y%m%d" gather_config=yes
