---
- hosts:
  - org
  gather_facts: no
  vars:
    ansible_connection: local
  vars_files:
    - "~/.clicap.vault.yml"
  tasks:
  - name: collect the output of all relevant operating system commands
    action: clicap output="/tmp/clicap-%Y%m%d" no_host_key_check=yes on_error=continue
